alias sqlplus='rlwrap --history-no-dupes 2 sqlplus64'
alias vis='vim -R ~/templates/sql_template.sql'
alias vic='vim -R ~/templates/template.ctl'
alias vipl='vim -R ~/templates/template.sql'
alias vish='vim -R ~/templates/template.sh'
alias mjhead='jhead -autorot -nf%Y%m%d_%H%M%S'
