alias sqlplus='rlwrap --history-no-dupes 2 sqlplus64'
alias vis='vim -R ~/unix/templates/sql_template.sql'
alias vic='vim -R ~/unix/templates/template.ctl'
alias vipl='vim -R ~/unix/templates/template.sql'
alias vish='vim -R ~/unix/templates/template.sh'
alias mjhead='jhead -autorot -nf%Y%m%d_%H%M%S'
alias am='ssh -i /home/shmyg/.ssh/AWSFirstInstance.pem ubuntu@ec2-18-234-222-4.compute-1.amazonaws.com'
